In [1]:
import pandas as pd

In [6]:
data = {
    "Product": ["Laptop", "Mouse", "Keyboard", "Monitor"],
    "Price": [45000, 800, 1500, 12000],
    "Stock": [15, 50, 30, 20]
}

In [8]:
df = pd.DataFrame(data, index=["P001", "P002", "P003", "P004"])
df

       Product  Price  Stock
P001    Laptop  45000     15
P002     Mouse    800     50
P003  Keyboard   1500     30
P004   Monitor  12000     20

In [10]:
df = df.set_index("Product")
df

          Price  Stock
Product
Laptop    45000     15
Mouse       800     50
Keyboard   1500     30
Monitor   12000     20

In [ ]:
df = pd.DataFrame(data, columns=["Product", "Price"])
df