In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("netflix_titles.csv")

In [3]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,33 min,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [4]:
df.shape

(8807, 12)

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   str
 1   type          8807 non-null   str
 2   title         8807 non-null   str
 3   director      6173 non-null   str
 4   cast          7982 non-null   str
 5   country       7976 non-null   str
 6   date_added    8797 non-null   str
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   str
 9   duration      8804 non-null   str
 10  listed_in     8807 non-null   str
 11  description   8807 non-null   str
dtypes: int64(1), str(11)
memory usage: 825.8 KB

In [6]:
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='str')

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df = df.drop_duplicates()
df.shape

(8807, 12)

In [9]:
df["show_id"].head()

0    s1
1    s2
2    s3
3    s4
4    s5
Name: show_id, dtype: str

In [10]:
df = df.drop(columns=["show_id"])
df.shape

(8807, 11)

In [11]:
df.columns

Index(['type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='str')

In [12]:
df = df.rename(columns={
    "listed_in": "genre",
    "date_added": "date_added_on_netflix"
})
df.columns

Index(['type', 'title', 'director', 'cast', 'country', 'date_added_on_netflix',
       'release_year', 'rating', 'duration', 'genre', 'description'],
      dtype='str')

In [13]:
df = df.reset_index(drop=True)
df.head()

,type,title,director,cast,country,date_added_on_netflix,release_year,rating,duration,genre,description
0,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,33 min,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [14]:
df

,type,title,director,cast,country,date_added_on_netflix,release_year,rating,duration,genre,description
0,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,33 min,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...
8802,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [15]:
df.columns = df.columns.str.upper()
df.columns

Index(['TYPE', 'TITLE', 'DIRECTOR', 'CAST', 'COUNTRY', 'DATE_ADDED_ON_NETFLIX',
       'RELEASE_YEAR', 'RATING', 'DURATION', 'GENRE', 'DESCRIPTION'],
      dtype='str')

In [16]:
df

,TYPE,TITLE,DIRECTOR,CAST,COUNTRY,DATE_ADDED_ON_NETFLIX,RELEASE_YEAR,RATING,DURATION,GENRE,DESCRIPTION
0,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,33 min,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...
8802,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [17]:
df.isnull().sum()

TYPE                        0
TITLE                       0
DIRECTOR                 2634
CAST                      825
COUNTRY                   831
DATE_ADDED_ON_NETFLIX      10
RELEASE_YEAR                0
RATING                      4
DURATION                    3
GENRE                       0
DESCRIPTION                 0
dtype: int64

In [18]:
df.isnull().sum() / len(df) * 100

TYPE                      0.000000
TITLE                     0.000000
DIRECTOR                 29.908028
CAST                      9.367549
COUNTRY                   9.435676
DATE_ADDED_ON_NETFLIX     0.113546
RELEASE_YEAR              0.000000
RATING                    0.045418
DURATION                  0.034064
GENRE                     0.000000
DESCRIPTION               0.000000
dtype: float64

## Handling - director column

In [19]:
df["DIRECTOR"] = df["DIRECTOR"].fillna("Unknown")
df["DIRECTOR"].isnull().sum()

np.int64(0)

## Handling - country column

In [20]:
df["COUNTRY"].mode()[0]

'United States'

In [21]:
df["COUNTRY"] = df["COUNTRY"].fillna(df["COUNTRY"].mode()[0])
df["COUNTRY"].isnull().sum()

np.int64(0)

## Handling - date_added, rating and duration

In [22]:
df = df.dropna(subset=["DATE_ADDED_ON_NETFLIX", "RATING", "DURATION"])
df.isnull().sum()

TYPE                       0
TITLE                      0
DIRECTOR                   0
CAST                     825
COUNTRY                    0
DATE_ADDED_ON_NETFLIX      0
RELEASE_YEAR               0
RATING                     0
DURATION                   0
GENRE                      0
DESCRIPTION                0
dtype: int64

## Handling - cast column

In [23]:
df["CAST"] = df["CAST"].fillna("Unknown")
df.isnull().sum()

TYPE                     0
TITLE                    0
DIRECTOR                 0
CAST                     0
COUNTRY                  0
DATE_ADDED_ON_NETFLIX    0
RELEASE_YEAR             0
RATING                   0
DURATION                 0
GENRE                    0
DESCRIPTION              0
dtype: int64

In [24]:
df

,TYPE,TITLE,DIRECTOR,CAST,COUNTRY,DATE_ADDED_ON_NETFLIX,RELEASE_YEAR,RATING,DURATION,GENRE,DESCRIPTION
0,Movie,Dick Johnson Is Dead,Kirsten Johnson,Unknown,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,TV Show,Blood & Water,Unknown,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",United States,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,TV Show,Jailbirds New Orleans,Unknown,Unknown,United States,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,TV Show,Kota Factory,Unknown,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,33 min,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...
8802,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,TV Show,Zombie Dumb,Unknown,Unknown,United States,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [25]:
df.info()

<class 'pandas.DataFrame'>
Index: 8790 entries, 0 to 8806
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   TYPE                   8790 non-null   str
 1   TITLE                  8790 non-null   str
 2   DIRECTOR               8790 non-null   str
 3   CAST                   8790 non-null   str
 4   COUNTRY                8790 non-null   str
 5   DATE_ADDED_ON_NETFLIX  8790 non-null   str
 6   RELEASE_YEAR           8790 non-null   int64
 7   RATING                 8790 non-null   str
 8   DURATION               8790 non-null   str
 9   GENRE                  8790 non-null   str
 10  DESCRIPTION            8790 non-null   str
dtypes: int64(1), str(10)
memory usage: 824.1 KB

## Clean the date_added_on_netflix column

In [26]:
df["DATE_ADDED_ON_NETFLIX"] = df["DATE_ADDED_ON_NETFLIX"].str.strip()
df["DATE_ADDED_ON_NETFLIX"] = pd.to_datetime(df["DATE_ADDED_ON_NETFLIX"])
df["DATE_ADDED_ON_NETFLIX"].dtype

dtype('<M8[us]')

In [27]:
df.info()

<class 'pandas.DataFrame'>
Index: 8790 entries, 0 to 8806
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   TYPE                   8790 non-null   str
 1   TITLE                  8790 non-null   str
 2   DIRECTOR               8790 non-null   str
 3   CAST                   8790 non-null   str
 4   COUNTRY                8790 non-null   str
 5   DATE_ADDED_ON_NETFLIX  8790 non-null   datetime64[us]
 6   RELEASE_YEAR           8790 non-null   int64
 7   RATING                 8790 non-null   str
 8   DURATION               8790 non-null   str
 9   GENRE                  8790 non-null   str
 10  DESCRIPTION            8790 non-null   str
dtypes: datetime64[us](1), int64(1), str(9)
memory usage: 824.1 KB

In [28]:
df["YEAR_ADDED"] = df["DATE_ADDED_ON_NETFLIX"].dt.year
df["MONTH_ADDED"] = df["DATE_ADDED_ON_NETFLIX"].dt.month
df[["DATE_ADDED_ON_NETFLIX", "YEAR_ADDED", "MONTH_ADDED"]].head()

  DATE_ADDED_ON_NETFLIX  YEAR_ADDED  MONTH_ADDED
0            2021-09-25        2021            9
1            2021-09-24        2021            9
2            2021-09-24        2021            9
3            2021-09-24        2021            9
4            2021-09-24        2021            9

## Clean the rating column

In [29]:
df["RATING"].unique()

<StringArray>
[   'PG-13',    'TV-MA',   '33 min',       'PG',    'TV-14',    'TV-PG',
     'TV-Y',    'TV-Y7',   '88 min',   '91 min',        'R',     'TV-G',
   '75 min',        'G',  '125 min',    'NC-17',       'NR', 'TV-Y7-FV',
       'UR']
Length: 19, dtype: str

In [30]:
df["RATING"] = df["RATING"].replace(r"\d+\s*min", pd.NA, regex=True)

In [31]:
df["RATING"] = df["RATING"].fillna(df["RATING"].mode()[0])
df["RATING"].unique()

<StringArray>
[   'PG-13',    'TV-MA',       'PG',    'TV-14',    'TV-PG',     'TV-Y',
    'TV-Y7',        'R',     'TV-G',        'G',    'NC-17',       'NR',
 'TV-Y7-FV',       'UR']
Length: 14, dtype: str

In [32]:
df.info()

<class 'pandas.DataFrame'>
Index: 8790 entries, 0 to 8806
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   TYPE                   8790 non-null   str
 1   TITLE                  8790 non-null   str
 2   DIRECTOR               8790 non-null   str
 3   CAST                   8790 non-null   str
 4   COUNTRY                8790 non-null   str
 5   DATE_ADDED_ON_NETFLIX  8790 non-null   datetime64[us]
 6   RELEASE_YEAR           8790 non-null   int64
 7   RATING                 8790 non-null   str
 8   DURATION               8790 non-null   str
 9   GENRE                  8790 non-null   str
 10  DESCRIPTION            8790 non-null   str
 11  YEAR_ADDED             8790 non-null   int32
 12  MONTH_ADDED            8790 non-null   int32
dtypes: datetime64[us](1), int32(2), int64(1), str(9)
memory usage: 892.7 KB