In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame({
   "OrderID":  ["O_001", "O_002", "O_003", "O_004", "O_005",
                "O_006", "O_007", "O_008", "O_009", "O_010"],
   "Customer": ["Cust_A", "Cust_B", "Cust_C", "Cust_D", "Cust_E",
                "Cust_F", "Cust_G", "Cust_H", "Cust_I", "Cust_J"],
   "Product":  ["Laptop", "Mouse", "Keyboard", "Monitor", "Webcam",
                "Headset", "Laptop", "Mouse", "Monitor", "Keyboard"],
   "Amount":   [45000, 800, 1500, 12000, 2500,
                3500, 47000, 750, 11500, 1400],
   "Status":   ["Delivered", "Pending", "Delivered", "Shipped", "Delivered",
                "Pending", "Delivered", "Shipped", "Delivered", "Pending"]
})
df

  OrderID Customer   Product  Amount     Status
0   O_001   Cust_A    Laptop   45000  Delivered
1   O_002   Cust_B     Mouse     800    Pending
2   O_003   Cust_C  Keyboard    1500  Delivered
3   O_004   Cust_D   Monitor   12000    Shipped
4   O_005   Cust_E    Webcam    2500  Delivered
5   O_006   Cust_F   Headset    3500    Pending
6   O_007   Cust_G    Laptop   47000  Delivered
7   O_008   Cust_H     Mouse     750    Shipped
8   O_009   Cust_I   Monitor   11500  Delivered
9   O_010   Cust_J  Keyboard    1400    Pending

In [3]:
res = df.loc[(df["Status"] == "Delivered") & (df["Amount"] <= 10000)]
display(res)
print(f"Total rows: {len(res)}")

  OrderID Customer   Product  Amount     Status
2   O_003   Cust_C  Keyboard    1500  Delivered
4   O_005   Cust_E    Webcam    2500  Delivered

Total rows: 2

In [4]:
res = np.where(df["Status"] == "Pending")[0]
display(df.loc[res,["Customer", "Product", "Status"]])

  Customer   Product   Status
1   Cust_B     Mouse  Pending
5   Cust_F   Headset  Pending
9   Cust_J  Keyboard  Pending

In [5]:
res = df.loc[(df["Status"] == "Shipped") | (df["Amount"] < 1000)]
display(res)

  OrderID Customer  Product  Amount   Status
1   O_002   Cust_B    Mouse     800  Pending
3   O_004   Cust_D  Monitor   12000  Shipped
7   O_008   Cust_H    Mouse     750  Shipped